### ISSUE TITLE
Thanks for this starting point!

### ISSUE THREAD

**Issue by NetOpWibby** [bowen31337/electron-rollup-kickstart#1]
It really helped me figure out how to use Electron the way I wanted to. I had to update/change a lot of things, check it out here if you interested! https://code.webb.page/Starters/electron-starter

(:

**Comment by pjebs** [comment]
@NetOperatorWibby How did you get rollup to work?
Did you have to configure rollup differently for main process (node.js) vs renderer (browser)?

**Comment by NetOpWibby** [comment]
@pjebs Ah, I see my link above is dead. Here's the new link: https://code.webb.page/Starters/electron-starter. And here's a TypeScript one I forgot I made. Unsure if it works: https://code.webb.page/Starters/electron-typescript-starter

**Comment by samuelkubai** [comment]
@NetOperatorWibby could you share and updated link of how you got rollup to work?

**Comment by NetOpWibby** [comment]
@samuelkubai Idk if this still works tbh https://github.com/NetOperatorWibby/electron-typescript-starter

**Comment by samuelkubai** [comment]
Hi @NetOperatorWibby, was actually more interested with the rollup starter project.

**Comment by NetOpWibby** [comment]
https://github.com/NetOperatorWibby/electron-starter

**Comment by samuelkubai** [comment]
Thank you @NetOperatorWibby
